apiVersion: v2
appVersion: 2.2.0
dependencies:
- condition: opentelemetry-collector.enabled
  name: opentelemetry-collector
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  version: 0.142.2
- condition: jaeger.enabled
  name: jaeger
  repository: https://jaegertracing.github.io/helm-charts
  version: 4.3.0
- condition: prometheus.enabled
  name: prometheus
  repository: https://prometheus-community.github.io/helm-charts
  version: 28.2.0
- condition: grafana.enabled
  name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 10.5.8
- condition: opensearch.enabled
  name: opensearch
  repository: https://opensearch-project.github.io/helm-charts/
  version: 3.4.0
description: opentelemetry demo helm chart
home: https://opentelemetry.io/
icon: https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png
maintainers:
- name: dmitryax
- name: jaronoff97
- name: julianocosta89
- name: puckpuck
- name: tylerhelmuth
name: opentelemetry-demo
sources:
- https://github.com/open-telemetry/opentelemetry-demo
type: application
version: 0.40.2
