annotations:
  artifacthub.io/changes: '- Add securityContext.sysctls options (#337)'
apiVersion: v2
appVersion: 3.2.5
description: A Helm chart for HAProxy Kubernetes Ingress Controller
home: https://github.com/haproxytech/helm-charts/tree/main/kubernetes-ingress
icon: https://raw.githubusercontent.com/haproxytech/helm-charts/main/kubernetes-ingress/chart-icon.png
keywords:
- ingress
- haproxy
kubeVersion: '>=1.23.0-0'
maintainers:
- email: dkorunic@haproxy.com
  name: Dinko Korunic
name: kubernetes-ingress
sources:
- https://github.com/haproxytech/kubernetes-ingress
type: application
version: 1.48.0
