apiVersion: v2
appVersion: 2.14.1
dependencies:
- condition: provisionDataStore.cassandra
  name: cassandra
  repository: https://charts.helm.sh/incubator
  version: 0.15.3
- condition: provisionDataStore.elasticsearch
  name: elasticsearch
  repository: https://helm.elastic.co
  version: 8.5.1
- name: common
  repository: https://charts.bitnami.com/bitnami
  version: 2.x.x
description: A Jaeger Helm chart for Kubernetes
home: https://jaegertracing.io
icon: https://www.jaegertracing.io/img/jaeger-icon-reverse-color.svg
keywords:
- jaeger
- opentracing
- tracing
- instrumentation
kubeVersion: '>= 1.21-0'
maintainers:
- email: ankit.mehta@appian.com
  name: mehta-ankit
- email: michael.lorant@fairfaxmedia.com.au
  name: mikelorant
- email: naseem@transit.app
  name: naseemkullah
- email: me@pavelnikolov.net
  name: pavelnikolov
- email: jkowall@kowall.net
  name: jkowall
name: jaeger
sources:
- https://hub.docker.com/u/jaegertracing/
type: application
version: 4.3.0
