apiVersion: v2
appVersion: 2.17.0
dependencies:
- name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  version: <= 4.4.0
description: A Helm chart for Kubernetes
name: antmedia
type: application
version: 2.17.0
