annotations:
  artifacthub.io/changes: |
    - kind: security
      description: |
        fix(deps): switch injector to openbao-k8s with patched golang.org/x/crypto (CVE-2024-45337)
  artifacthub.io/containsSecurityUpdates: "true"
  charts.openshift.io/name: Openbao
apiVersion: v2
appVersion: v2.4.4
description: Official OpenBao Chart
home: https://github.com/openbao/openbao-helm
icon: https://github.com/openbao/artwork/blob/main/color/openbao-color.svg
keywords:
- vault
- openbao
- security
- encryption
- secrets
- management
- automation
- infrastructure
kubeVersion: '>= 1.30.0-0'
maintainers:
- email: openbao-security@lists.openssf.org
  name: OpenBao
  url: https://openbao.org
name: openbao
sources:
- https://github.com/openbao/openbao-helm
version: 0.23.3
